apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: finai-cert
  namespace: finai
spec:
  secretName: finai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - app.staging.finai.com
